project_id = "iiedvevrmrljiaqwgrsa"

[functions.create-booking]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = false

[functions.request-demo]
verify_jwt = false

[functions.approve-demo]
verify_jwt = false

[functions.reject-demo]
verify_jwt = false

[functions.send-session-link]
verify_jwt = false
